---
Name: consolermiddleware
After:
  - requestprocessors
Only:
  environment: 'dev'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        clie\middleware\ConsolerMiddleware: '%$clie\middleware\ConsolerMiddleware'
